#CentOS Docker file with Ssh 
#VERSION 0.0.1

#Base Image
FROM centos/systemd

#Maintainer Info.
LABEL maintainer="juxtap.se@gmail.com"

#Update APT repository & Install OpenSSH
RUN yum install openssh-server -y

#Allow Password && Root login
#Allow Root login
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

#set password
RUN echo "root:root" | chpasswd

RUN mkdir /root/.ssh

#To start service at runtime
CMD ["/usr/sbin/sshd", "-D"]